"""Dynamic tile serving via TiTiler — Cloud-Optimized GeoTIFF (COG) rendering."""

from datetime import date
from pathlib import Path

from fastapi import APIRouter, HTTPException, Query, status
from fastapi.responses import FileResponse, Response
from rio_tiler.errors import TileOutsideBounds
from rio_tiler.io import COGReader
from titiler.core.factory import TilerFactory

from backend.data_loader import get_layer
from backend.raster_rendering import colorize, render_png

router = APIRouter(tags=["tiles"])

# ===== TiTiler dynamic COG tile engine =====
# All endpoints under /cog are auto-generated by TilerFactory:
#   GET  /cog/tiles/{z}/{x}/{y}.{ext}
#   GET  /cog/info
#   etc.

cog = TilerFactory(router_prefix="/cog")
cog_tiler = cog.router

# ===== SSM Tiles =====
# Maps human-readable time strings (8day dates, monthly, period index) to COG paths,
# then renders the tile locally with the layer metadata palette.
# Frontend uses: /data/ssm-tiles/{tileMatrixSetId}/{z}/{x}/{y}.png?time=2010-02-02

# Project root is two levels up from routers/tiles.py → backend/routers/ → project/
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent

# Small transparent PNG (1×1 pixel) returned for out-of-bounds or missing tiles
TRANSPARENT_PNG = (
    b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01"
    b"\x08\x06\x00\x00\x00\x1f\x15\xc4\x89\x00\x00\x00\nIDATx\x9cc\x00"
    b"\x01\x00\x00\x05\x00\x01\r\n\xb4\x00\x00\x00\x00IEND\xaeB`\x82"
)


def _ssm_time_to_cog_name(time: str) -> str:
    """Convert a time string to SSM COG filename (e.g., '2010-02-02' → '2010_05_cog.tif')."""
    if "_" in time:
        return f"{time}_cog.tif"
    if len(time) == 10:
        year_s = int(time[:4])
        month_s = int(time[5:7])
        day_s = int(time[8:10])
        d = date(year_s, month_s, day_s)
        start = date(year_s, 1, 1)
        period = (d - start).days // 8 + 1
        return f"{year_s}_{period:02d}_cog.tif"
    if len(time) == 7:
        year_s = int(time[:4])
        month_s = int(time[5:7])
        d = date(year_s, month_s, 15)
        start = date(year_s, 1, 1)
        period = (d - start).days // 8 + 1
        return f"{year_s}_{period:02d}_cog.tif"
    return f"{time}_cog.tif"


def _render_ssm_tile(cog_path: Path, x: int, y: int, z: int) -> bytes:
    """Render one SSM COG tile using the shared metadata legend and source mask."""
    layer = get_layer("ssm")
    if layer is None:
        raise RuntimeError("SSM layer metadata is missing")
    legend = layer.get("legend")
    if not legend:
        raise RuntimeError("SSM layer legend is missing or empty")
    with COGReader(str(cog_path)) as reader:
        image = reader.tile(x, y, z, indexes=1)
    rgba = colorize(image.data[0], legend, source_mask=image.mask)
    return render_png(rgba)


@router.get("/ssm-tiles/{tileMatrixSetId}/{z}/{x}/{y}.png")
def ssm_tile_proxy(
    tileMatrixSetId: str,
    z: int, x: int, y: int,
    time: str = Query(...),
):
    """Resolve an SSM time to a COG, render it locally, and return PNG bytes."""
    if tileMatrixSetId != "WebMercatorQuad":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(
                f"Unsupported tile matrix set '{tileMatrixSetId}'; "
                "only WebMercatorQuad is supported"
            ),
        )
    cog_name = _ssm_time_to_cog_name(time)
    cog_rel = f"data/rasters/ssm/{cog_name}"
    cog_path = PROJECT_ROOT / cog_rel
    if not cog_path.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"COG file not found for time '{time}' (looked for: {cog_name})",
        )
    try:
        png = _render_ssm_tile(cog_path, x, y, z)
    except TileOutsideBounds:
        png = TRANSPARENT_PNG
    return Response(content=png, media_type="image/png")


# ===== Legacy static tile serving (for pre-generated PNG tiles of non-SSM layers) =====

TILES_ROOT = PROJECT_ROOT / "data" / "tiles"


@router.get("/tiles/{layer}/{time}/{z}/{x}/{y}.png")
def serve_static_tile(layer: str, time: str, z: int, x: int, y: int):
    """Serve a pre-generated raster tile image (legacy path for non-SSM layers)."""
    tile_path = TILES_ROOT / layer / time / str(z) / str(x) / f"{y}.png"
    if not tile_path.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Tile not found: {tile_path}",
        )
    return FileResponse(tile_path, media_type="image/png")
