"""Dynamic tile serving via TiTiler — Cloud-Optimized GeoTIFF (COG) rendering."""

from pathlib import Path

from fastapi import APIRouter, HTTPException, status
from fastapi.responses import FileResponse
from titiler.core.factory import TilerFactory

router = APIRouter(tags=["tiles"])

# ===== TiTiler dynamic COG tile engine =====
# All endpoints under /cog are auto-generated by TilerFactory:
#   GET  /cog/tiles/{z}/{x}/{y}.{ext}
#   GET  /cog/info
#   etc.
# Frontend uses: /cog/tiles/{z}/{x}/{y}.png?url=data/rasters/ssm/2010_05_cog.tif&colormap_name=rdylgn&rescale=0.0,0.5

cog = TilerFactory(router_prefix="/cog")
cog_tiler = cog.router

# ===== Legacy static tile serving (for pre-generated PNG tiles of non-SSM layers) =====

# Project root is two levels up from routers/tiles.py → backend/routers/ → project/
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
TILES_ROOT = PROJECT_ROOT / "data" / "tiles"


@router.get("/tiles/{layer}/{time}/{z}/{x}/{y}.png")
def serve_static_tile(layer: str, time: str, z: int, x: int, y: int):
    """Serve a pre-generated raster tile image (legacy path for non-SSM layers)."""
    tile_path = TILES_ROOT / layer / time / str(z) / str(x) / f"{y}.png"
    if not tile_path.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Tile not found: {tile_path}",
        )
    return FileResponse(tile_path, media_type="image/png")
