"""Dynamic tile serving via TiTiler — Cloud-Optimized GeoTIFF (COG) rendering."""

from pathlib import Path

from fastapi import APIRouter, HTTPException, Query, status
from fastapi.responses import FileResponse, Response
from rio_tiler.errors import TileOutsideBounds
from rio_tiler.io import COGReader
from titiler.core.factory import TilerFactory

from backend.data_loader import (
    IRRIGATION_8DAY_ROOT,
    IRRIGATION_ANNUAL_ROOT,
    IRRIGATION_ANNUAL_COG_ROOT,
    IRRIGATION_8DAY_COG_ROOT,
    get_irrigation_layer,
    get_layer,
)
from backend.irrigation_time import irrigation_time_to_cog_path, irrigation_time_to_path
from backend.irrigation_legend import get_irrigation_dynamic_legend, valid_irrigation_mask
from backend.raster_rendering import colorize, render_png
from backend.ssm_legend import get_dynamic_legend
from backend.ssm_time import ssm_time_to_cog_path

router = APIRouter(tags=["tiles"])

# ===== TiTiler dynamic COG tile engine =====
# All endpoints under /cog are auto-generated by TilerFactory:
#   GET  /cog/tiles/{z}/{x}/{y}.{ext}
#   GET  /cog/info
#   etc.

cog = TilerFactory(router_prefix="/cog")
cog_tiler = cog.router

# ===== SSM Tiles =====
# Maps human-readable time strings (8day dates, monthly, period index) to COG paths,
# then renders the tile locally with the layer metadata palette.
# Frontend uses: /data/ssm-tiles/{tileMatrixSetId}/{z}/{x}/{y}.png?time=2010-02-02

# Project root is two levels up from routers/tiles.py → backend/routers/ → project/
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent

# Small transparent PNG (1×1 pixel) returned for out-of-bounds or missing tiles
TRANSPARENT_PNG = (
    b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01"
    b"\x08\x06\x00\x00\x00\x1f\x15\xc4\x89\x00\x00\x00\nIDATx\x9cc\x00"
    b"\x01\x00\x00\x05\x00\x01\r\n\xb4\x00\x00\x00\x00IEND\xaeB`\x82"
)


def _render_ssm_tile(cog_path: Path, x: int, y: int, z: int) -> bytes:
    """Render one SSM COG tile using the shared metadata legend and source mask."""
    layer = get_layer("ssm")
    if layer is None:
        raise RuntimeError("SSM layer metadata is missing")
    base_legend = layer.get("legend")
    if not base_legend:
        raise RuntimeError("SSM layer legend is missing or empty")
    legend = get_dynamic_legend(cog_path, base_legend, layer.get("unit") or "")

    # Parse nodata color from layer config with defaults
    nodata_color_hex = layer.get("nodataColor", "#e8e8e8")
    nodata_opacity = float(layer.get("nodataOpacity", 0.5))
    try:
        nodata_rgb = tuple(bytes.fromhex(nodata_color_hex.lstrip("#")))
        nodata_alpha = int(round(nodata_opacity * 255))
        nodata_color = (*nodata_rgb, nodata_alpha)
    except (ValueError, TypeError):
        nodata_color = (0xE8, 0xE8, 0xE8, 128)

    with COGReader(str(cog_path)) as reader:
        image = reader.tile(x, y, z, indexes=1)
    rgba = colorize(
        image.data[0], legend, source_mask=image.mask, nodata_color=nodata_color
    )
    return render_png(rgba)


@router.get("/ssm-tiles/{tileMatrixSetId}/{z}/{x}/{y}.png")
def ssm_tile_proxy(
    tileMatrixSetId: str,
    z: int, x: int, y: int,
    time: str = Query(...),
):
    """Resolve an SSM time to a COG, render it locally, and return PNG bytes."""
    if tileMatrixSetId != "WebMercatorQuad":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(
                f"Unsupported tile matrix set '{tileMatrixSetId}'; "
                "only WebMercatorQuad is supported"
            ),
        )
    try:
        cog_path = ssm_time_to_cog_path(
            PROJECT_ROOT / "data" / "rasters" / "ssm", time
        )
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=str(exc),
        ) from exc
    cog_name = cog_path.name
    if not cog_path.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"COG file not found for time '{time}' (looked for: {cog_name})",
        )
    try:
        png = _render_ssm_tile(cog_path, x, y, z)
    except TileOutsideBounds:
        png = TRANSPARENT_PNG
    return Response(content=png, media_type="image/png")


# ===== Irrigation water tiles =====


def _render_irrigation_tile(raster_path: Path, x: int, y: int, z: int, time: str = "") -> bytes:
    """Render one irrigation water raster tile using the irrigation legend."""
    layer = get_irrigation_layer()
    base_legend = layer.get("legend")
    if not base_legend:
        raise RuntimeError("Irrigation layer legend is missing or empty")
    legend = get_irrigation_dynamic_legend(raster_path, base_legend, layer.get("unit") or "", time=time)
    nodata_color = (0xE8, 0xE8, 0xE8, 128)
    with COGReader(str(raster_path)) as reader:
        image = reader.tile(x, y, z, indexes=1)
    source_mask = image.mask & valid_irrigation_mask(image.data[0])
    rgba = colorize(
        image.data[0],
        legend,
        source_mask=source_mask,
        nodata_color=nodata_color,
    )
    return render_png(rgba)


@router.get("/irrigation-tiles/{tileMatrixSetId}/{z}/{x}/{y}.png")
def irrigation_tile_proxy(
    tileMatrixSetId: str,
    z: int,
    x: int,
    y: int,
    time: str = Query(...),
):
    """Resolve an irrigation time to a configured raster and render a PNG tile."""
    if tileMatrixSetId != "WebMercatorQuad":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(
                f"Unsupported tile matrix set '{tileMatrixSetId}'; "
                "only WebMercatorQuad is supported"
            ),
        )
    try:
        raster_path = irrigation_time_to_cog_path(
            IRRIGATION_ANNUAL_ROOT,
            IRRIGATION_ANNUAL_COG_ROOT,
            IRRIGATION_8DAY_ROOT,
            IRRIGATION_8DAY_COG_ROOT,
            time,
        )
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=str(exc),
        ) from exc
    if not raster_path.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=(
                f"Irrigation raster not found for time '{time}' "
                f"(looked for: {raster_path.name})"
            ),
        )
    try:
        png = _render_irrigation_tile(raster_path, x, y, z, time=time)
    except TileOutsideBounds:
        png = TRANSPARENT_PNG
    return Response(content=png, media_type="image/png")


# ===== Legacy static tile serving (for pre-generated PNG tiles of non-SSM layers) =====

TILES_ROOT = PROJECT_ROOT / "data" / "tiles"


@router.get("/tiles/{layer}/{time}/{z}/{x}/{y}.png")
def serve_static_tile(layer: str, time: str, z: int, x: int, y: int):
    """Serve a pre-generated raster tile image (legacy path for non-SSM layers)."""
    tile_path = TILES_ROOT / layer / time / str(z) / str(x) / f"{y}.png"
    if not tile_path.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Tile not found: {tile_path}",
        )
    return FileResponse(tile_path, media_type="image/png")
